### ISSUE TITLE
 "Unexpected token *"

### ISSUE THREAD

**Issue by aaronmcohen** [angular/dgeni#127]
I as trying out Dgeni against a [KoaJS](http://koajs.com/) application however it seems to having trouble with this

app.use(function *(){
	  this.body = 'Hello World';
});

The exact error is  "Unexpected token *" and it passes eslint. 

Is there a special setting I need to use?

**Comment by hco** [comment]
I assume that this is related to #122, as generators are a ES6 feature.

**Comment by aaronmcohen** [comment]
Looks like it is related to the ES6 support.  Thank you!

**Comment by petebacondarwin** [comment]
Closing as a dupe of #122
