### ISSUE TITLE
Unexpected reserved word

### ISSUE THREAD

**Issue by wesleycho** [angular/dgeni#129]
I get this error when trying to run dgeni on source files written in ES6 - in particular, the `export` statement at the beginning of a script.

This should not error out on ES6 scripts

**Comment by wesleycho** [comment]
Investigating this further, this looks like because esprima does not support ES6.

**Comment by hco** [comment]
Seems to be a duplicate of #122

**Comment by forresst** [comment]
@wesleycho You are right. Does it take to replace [Esprima](https://github.com/jquery/esprima) by [Espree](https://github.com/eslint/espree). This is done for [jsdoc](https://github.com/jsdoc3/jsdoc/commit/04559dbe7d6c61303d639575741dffbdac9ef300).
What's your opinion @petebacondarwin ?

**Comment by petebacondarwin** [comment]
I will update to dgeni-packages to use Espree. Closing as a duplicate of #122
