### ISSUE TITLE
Markdown Support

### ISSUE THREAD

**Issue by Kesymaru** [angular/dgeni#131]
Hello.

I have been playing with dgeni + angular and i have noticed that @description tag does not support markdown.

I would like to know if is possible to add Markdown support on the @description tag.

**Comment by petebacondarwin** [comment]
It does support markdown, can you give a concrete example of what you are trying to do?

**Comment by Kesymaru** [comment]
ok.

I am trying to make the documentation for an angular based project, then i have a service when i try to use a @description like this:

```javascript
(function(){

    angular.module('mod1.advancedSearch', [])
    .factory('advanced.search', [
        '$http'.
        advancedService
    ]);
    
    /**
    * @ngdoc service
    * @name advanced.search
    * @description
    * # Advanced Search Service
    */
    function advancedService($http){
        var service = {
            get: get
        };
        
        /**
        * @name get
        * @methodOf advanced.search
        * @param {int} id
        */
        function get(id){

        };

        return service;
    };
})();
```
Result:
![capture](https://cloud.githubusercontent.com/assets/751342/8342717/644b2602-1a8b-11e5-9001-e342c4b6ef9a.PNG)

I also have noticed that if i change the @description to use HTML then it renders the HTML tag correctly, but not the Markdown.

**Comment by petebacondarwin** [comment]
So the markdown rendering should be done in your template. Can you provide that?

**Comment by Kesymaru** [comment]
Yeah.

I am using the template included by default on the [dgeni-angular example](https://github.com/petebacondarwin/dgeni-angular/tree/master/docs/templates)

I would like more template documentation, i want to create a template with sections like grunt ng-docs does but using dgeni because is more flexible.

**Comment by petebacondarwin** [comment]
Right, so this line (https://github.com/petebacondarwin/dgeni-angular/blob/master/docs/templates/common.template.html#L7) needs to change from 

```
<p>{$ doc.description $}</p>
```

to

```
<p>{$ doc.description | marked $}</p>
```

Simple, eh?

**Comment by Kesymaru** [comment]
Ok. 

I will try it, just one question more, is there a template documentation?

Other question, how can i create sections, for example a API section including all modules, directives, services and controller.

**Comment by petebacondarwin** [comment]
Great. The templating is done by the Nunjucks engine. The documentation for it is here: https://mozilla.github.io/nunjucks/templating.html

If you want to create sections then I suggest that you need to create new document objects (in the `docs`) collection for each section, which contain a link to each of the docs in that section. You might like to tweak the paths of the documents accordingly to group them into folders.

Take a look at https://github.com/angular/dgeni-packages/blob/master/ngdoc/processors/generateComponentGroups.js for an example of this sort of thing.

**Comment by Kesymaru** [comment]
Ok.

Thanks.
