### ISSUE TITLE
Link resolution

### ISSUE THREAD

**Issue by keirlawson** [angular/dgeni#139]
My team are looking at moving to dgeni from [Docular](http://grunt-docular.com/) so that we can have more control over what the outputted docs look like and so that we aren't tied to Grunt.

Our current docular projects are structured such that there are links between one set of docular docs and another from another project.  This means that at the time of the docs being built these links are often broken, only to be fixed when the docs are merged later in the process.  Docular allows us to do this as broken links are only warnings and links obey a standard pattern making the URL of a given component in some other document predictable.

It seems that dgeni doesn't have this flexibility, so I'm wondering what the best approach for us is, so we attempt to override the link resolution service to make it behave more like docular's?

**Comment by petebacondarwin** [comment]
Contacting @keirlawson directly via email to discuss.
