### ISSUE TITLE
Dependencies issues

### ISSUE THREAD

**Issue by ivorobkalo** [angular/dgeni#144]
Now dgeni is published to npm with many dependencies that used to be too outdated. I believe it's easy to non-destructively update some of them to newer versions in package.json and publish a minor update to npm. (e.g. `winston` still comes with `ver. 0.7.2` from npm)

Since `ver. 3.5` npm tries to load dependencies as flat as possible so with outdated dependencies come many additional files to download/manage and it costs time.

**Comment by petebacondarwin** [comment]
Sounds like a good idea. Do you want to give it a shot?

**Comment by ivorobkalo** [comment]
I checked latest stable versions of dependencies and created a pull request to update them.
All tests passed successfully after an update.

I guess dgeni version should be increased to let changes pass to npm repository (not sure how it passes there)

**Comment by petebacondarwin** [comment]
Landed as 11a7ef3. Thanks.
I will bump the version and publish to npm

**Comment by ivorobkalo** [comment]
Thanks!
