### ISSUE TITLE
Add typescript to list of standard packages

### ISSUE THREAD

**Issue by clavecoder** [angular/dgeni#152]
The README section _Standard Dgeni Packages_ is missing the `typescript` package. It should be added:

https://github.com/angular/dgeni/blame/07c04d51456f99bdbb7f50877fdbfb92335ddf68/README.md#L281

Note: the `git` package is also missing, but, perhaps, that was intentional.

**Comment by petebacondarwin** [comment]
Good first PR...

**Comment by clavecoder** [comment]
Done: #153
