### ISSUE TITLE
move mocha @types to dev dependencies 

### ISSUE THREAD

**Issue by vlio20** [angular/dgeni#156]
Hi,
"@types/mocha": "^2.2.39", is currently a dependency of this package, where is should be a dev dependency.

**Comment by vlio20** [comment]
@petebacondarwin, can you tell when this will be released?

**Comment by petebacondarwin** [comment]
It has already been released as 0.4.3 (and then as 0.4.4) :-)

**Comment by petebacondarwin** [comment]
See https://github.com/angular/dgeni/blob/master/CHANGELOG.md
