### ISSUE TITLE
Render document in multiple output formats

### ISSUE THREAD

**Issue by dherges** [angular/dgeni#164]
Hi all, hi Pete,

just a question for the moment: is it possible to render the same document in two (or more) different output formats?

Say, I have one document and like to generate a `document.json` and `document.html` for it?

I tried and set up this [example repo](dherges/dgeni-playground) but only managed to get either the JSON or HTML. It seems like `computePathsProcessor` only picks up one path template. Also if that was going to work, then `templateFinder` would need to pick up a template based on the file extension. Does that work?

Config snippet is in file: [tools/dgeni/docs/index.js#L58-L82](https://github.com/dherges/dgeni-playground/blob/master/tools/dgeni/docs/index.js#L58-L82)

**Comment by petebacondarwin** [comment]
One way would be if you simply clone the document and change its outputPath
etc.

**Comment by dherges** [comment]
Yes, that seems to work!

The important part is to give a different `docType` and `id` for the copy.  Shortened sample code:

```js
module.exports = function createContentIndex() {
  return {
    $runAfter: ['paths-computed'],
    $runBefore: ['rendering-docs'],
    $process: function(docs) {
      // Which docs should be copied?
      const docsToCopy = docs.filter(doc => doc.docType === 'foobar');

      // Create an additional document for the content index
      docs.push(docsToCopy.map(doc => {
        return {
          id: doc.id + '_foo',
          // A different doc type, e.g. for selecting another rendering template
          docType: doc.docType + `_bar`,
          path: doc.path,
          // Say, it's a JSON instead of HTML
          outputPath: doc.outputPath.replace('.html', '.json),
          /* ... copy more props ... */
        };
      }));
    }
  }
};
```

**Comment by petebacondarwin** [comment]
Glad you got it working.
