### ISSUE TITLE
Paths have collided when do git clone

### ISSUE THREAD

**Issue by juliet-zhu** [angular/dgeni#170]
## Description
I got warning when use `git clone` command. Does anyone also see this problem?
## Enviroment
System: OSX 10.14.4
node: v10.12.0
git version 2.20.1 (Apple Git-117)
## Reproduce Command:
```
git clone git@github.com:angular/dgeni.git
```
## Error Output
```
Cloning into 'dgeni'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 6351 (delta 1), reused 3 (delta 1), pack-reused 6343
Receiving objects: 100% (6351/6351), 4.78 MiB | 517.00 KiB/s, done.
Resolving deltas: 100% (3488/3488), done.
warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'docs/fr_FR/guide/02 - Architecture/06 - Traitement complémentaire.md'
  'docs/fr_FR/guide/02 - Architecture/06 - Traitement complémentaire.md'
  'docs/fr_FR/guide/03 - Utilisation de Dgeni/03 - Personnalisation/04 - Définitions de balise.md'
  'docs/fr_FR/guide/03 - Utilisation de Dgeni/03 - Personnalisation/04 - Définitions de balise.md'
```
## Expected behavior
No warning

**Comment by petebacondarwin** [comment]
Thanks for the report @juliet-zhu.

I can't reproduce it locally :-( On my machine 

OS/X 10.14.4
Node 10.12.0

I get:

```
$ git clone git@github.com:angular/dgeni.git
Cloning into 'dgeni'...
remote: Enumerating objects: 8, done.
remote: Counting objects: 100% (8/8), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 6351 (delta 1), reused 3 (delta 1), pack-reused 6343
Receiving objects: 100% (6351/6351), 4.78 MiB | 5.57 MiB/s, done.
Resolving deltas: 100% (3488/3488), done.
```

It looks to me, from your error message that your OS is not able to cope with the accented french characters (e.g. é). There are actually only one of each of these files in the repo. So I think it is safe to ignore these warnings.

**Comment by juliet-zhu** [comment]
Thanks for your quick reply.
Since I can successfully clone the repo, no more issues here.
I found there are only one of each of these files in my cloned repo but there are two in Github. I'm just a little confused.
![image](https://user-images.githubusercontent.com/5061903/56874903-b7424b00-6a6f-11e9-91f5-05fce79856f2.png)

**Comment by petebacondarwin** [comment]
Thanks for clarifying that @juliet-zhu - I have deleted the files from the Github repository.
