### ISSUE TITLE
Use of deprecated optimist library which includes a vulnerable version of minimist

### ISSUE THREAD

**Issue by alvaro450** [angular/dgeni#181]
Optimist library has been deprecated and since it has an older version of minimist that has a vulnerability (below):
__proto__.y=Polluted Argument Handling Prototype Pollution Remote Property Manipulation

I suggest to replace optimist with yargs or with minimist directly.

**Comment by petebacondarwin** [comment]
Just released 0.4.14 which removes optimist.
